#!/bin/bash
#########################################################################
# PostgreSQL Auto Backupper (Hourly)                                    #
#                                                                       #
#   Automatically makes compressed xz backups of a database every hour, #
#   but only if the DB's contents have changed.                         #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################

cd /code/bettergist-collector/database/backups
sudo -u postgres pg_dump bettergist | xz -9 --threads=0 > bettergist-$(date +"%Y%m%d.%H").sql.xz

# Delete dupes. https://unix.stackexchange.com/a/192712/15780
md5sum bettergist*sql.xz | sort | awk 'BEGIN{lasthash = ""} $1 == lasthash {print $2} {lasthash = $1}' | xargs rm
