#!/bin/bash

## Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>
## License: MIT

# @see https://serverfault.com/a/37836/56309
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Error: You *MUST* run this as sudo or root!"
    echo ""
    exit 99
fi

DATE=$(date +"%Y-%m-%d")
HOUR=$(date +"%H")

if [[ ! -d "/snaps/daily/${DATE}" ]]; then
    btrfs subvolume snapshot / /snaps/daily/${DATE}
fi

btrfs subvolume snapshot / /snaps/daily/${DATE}/${HOUR}
