#!/bin/bash

## Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>
## License: MIT

cd /tmp

# Remove PHP temporary files
rm -f $(ls /tmp | grep -P '^[a-zA-Z0-9]{6}$')

# Remove PHPUnit temp files
rm -f /tmp/tmp.*

# Remove phpstan temp files
rm -rf /tmp/phpstan
