#!/usr/bin/env bash
#########################################################################
# PHP Temp file Cleaner                                                 #
#                                                                       #
#   Removes unnecessary PHP temp files.                                 #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################

cd /tmp

# Remove PHP temporary files
rm -f $(ls /tmp | grep -P '^[a-zA-Z0-9]{6}$')

# Remove PHPUnit temp files
rm -f /tmp/tmp.*

# Remove phpstan temp files
rm -rf /tmp/phpstan
