#!/bin/bash
#########################################################################
# ChangeLog Maker (lite)                                                #
#                                                                       #
#   Quickly creates CHANGELOG.md entries suitable for GitHub from       #
#   the repo's commit log.                                              #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################

if [ -z "$1" ]; then
    echo "Error: You must provide a git hash/tag/etc"
    echo "       e.g., changelog-maker-lite v1.0.0.."
    exit 1
fi

# @see https://stackoverflow.com/a/12900372/430062
git log --pretty=shortlog --date=iso --reverse "$1" | awk '{print "* ["$3" "$4" CDT] - " substr($0, index($0, $9))}'
