#!/bin/bash

## Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>
## License: MIT

rsync -rv --remove-source-files --exclude=composer /home/*/.cache/ /run/media/sinkhole/
for user in `ls /home`; do
    find /home/$user/.cache/ -type d -empty -delete
done

rm -rvf /var/cache/pacman/pkg/*

