#!/usr/bin/env bash

#########################################################################
# BTRFS Auto Snapshotter (Hourly)                                       #
#                                                                       #
#   Automatically purges every non-EN locale every day.                 #
#                                                                       #
#   NOTE: This has only tested on Arch Linux.  It might cripple your    #
#         distribution's package manager (missing files).               #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################


# @see https://serverfault.com/a/37836/56309
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Error: You *MUST* run this as sudo or root!"
    echo ""
    exit 99
fi

# Removes every locale except en_US.
LOCALES=$(ls -1 /usr/share/locale/ | grep -v ^en)

cd /usr/share/locale
for locale in $LOCALES; do
    rm -rvf $LOCALES
done
