#!/bin/bash

## Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>
## License: MIT


# @see https://serverfault.com/a/37836/56309
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Error: You *MUST* run this as sudo or root!"
    echo ""
    exit 99
fi

# Removes every locale except en_US.
LOCALES=$(ls -1 /usr/share/locale/ | grep -v ^en)

cd /usr/share/locale
for locale in $LOCALES; do
    rm -rvf $LOCALES
done
