#!/bin/bash
#########################################################################
# BTRFS Auto Snapshotter (Daily)                                        #
#                                                                       #
#   Automatically takes snapshots of / into                             #
#       /snaps/daily/YYYY-mm-dd                                         #
#   every day -and- deletes all the previous day's HOURLY snapshots.    #
#                                                                       #
# Part of HopeSeekr's BashScripts Collection                            #
# https://github.com/hopeseekr/BashScripts/                             #
#                                                                       #
# Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>          #
# GPG Fingerprint: 4BF8 2613 1C34 87AC D28F  2AD8 EB24 A91D D612 5690   #
#                                                                       #
# License: Creative Commons Attribution v4.0 International              #
#########################################################################

# @see https://serverfault.com/a/37836/56309
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Error: You *MUST* run this as sudo or root!"
    echo ""
    exit 99
fi

mkdir -p /snaps/daily
#btrfs subvolume snapshot / /snaps/daily/$(date +"%Y-%m-%d")

DATE=$(date +"%Y-%m-%d")
YESTERDAY=$(date --date=yesterday +"%Y-%m-%d")

SUBVOLUMES=$(btrfs subvol list / | grep @snapshots/daily/${YESTERDAY}/[0-9]* | awk '{ print $9 }'  | sed -e 's/@snapshots/\/snaps/')

for snapshot in ${SUBVOLUMES}; do
    btrfs subvolume delete --commit-after ${snapshot}
done
