#!/bin/bash

## Copyright © 2020 Theodore R. Smith <theodore@phpexperts.pro>
## License: MIT

# @see https://serverfault.com/a/37836/56309
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Error: You *MUST* run this as sudo or root!"
    echo ""
    exit 99
fi

mkdir -p /snaps/daily
#btrfs subvolume snapshot / /snaps/daily/$(date +"%Y-%m-%d")

DATE=$(date +"%Y-%m-%d")
YESTERDAY=$(date --date=yesterday +"%Y-%m-%d")

SUBVOLUMES=$(btrfs subvol list / | grep @snapshots/daily/${YESTERDAY}/[0-9]* | awk '{ print $9 }'  | sed -e 's/@snapshots/\/snaps/')

for snapshot in ${SUBVOLUMES}; do
    btrfs subvolume delete --commit-after ${snapshot}
done
